name: Release Drafter

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 표준 GitHub 자동 생성 토큰 사용
        with:
          config-name: release-note.yml
          target_commitish: 'main'  # "main" 브랜치를 기준으로 설정
